project_id = "ymxnrnaptbwecjeqrdxp"

[functions.track-ticket]
verify_jwt = false

[functions.send-email]
verify_jwt = true

[functions.send-sms]
verify_jwt = true

[functions.b2b-register]
verify_jwt = false

[functions.ocr-intake]
verify_jwt = true
